'use server';
/**
 * @fileOverview A Genkit flow for a versatile AI assistant.
 * Provides high-level text reasoning similar to OpenAI, Grok, or Cohere.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SmartAssistantInputSchema = z.object({
  query: z.string().describe('The user question or task for the assistant.'),
  context: z.string().optional().describe('Optional context or history for the query.'),
});
export type SmartAssistantInput = z.infer<typeof SmartAssistantInputSchema>;

const SmartAssistantOutputSchema = z.object({
  answer: z.string().describe('The comprehensive answer generated by the AI.'),
});
export type SmartAssistantOutput = z.infer<typeof SmartAssistantOutputSchema>;

export async function smartAssistant(input: SmartAssistantInput): Promise<SmartAssistantOutput> {
  return smartAssistantFlow(input);
}

const assistantPrompt = ai.definePrompt({
  name: 'assistantPrompt',
  input: { schema: SmartAssistantInputSchema },
  output: { schema: SmartAssistantOutputSchema },
  prompt: `You are a helpful, brilliant, and concise AI assistant. 
Your task is to provide expert answers to the following query.

{{#if context}}
Context provided: {{{context}}}
{{/if}}

User Query: {{{query}}}

Answer the query accurately, creatively, and thoroughly.`,
});

const smartAssistantFlow = ai.defineFlow(
  {
    name: 'smartAssistantFlow',
    inputSchema: SmartAssistantInputSchema,
    outputSchema: SmartAssistantOutputSchema,
  },
  async (input) => {
    const { output } = await assistantPrompt(input);
    return output!;
  }
);
